name: Deploy VS Code Extension

on:
  push:
    branches:
      - master
    paths:
      - 'packages/vscode/package.json'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment'
        required: false
        default: 'Manual deployment'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9.6.0
          run_install: false

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: |
          cd packages/vscode
          pnpm lint

      - name: Run Tests
        run: |
          cd packages/vscode
          pnpm test

      - name: Build VS Code extension
        run: |
          cd packages/vscode
          pnpm build

      - name: Publish to VS Code Marketplace
        continue-on-error: true
        run: |
          cd packages/vscode
          npx @vscode/vsce publish --no-dependencies -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX Registry
        continue-on-error: true
        run: |
          cd packages/vscode
          npx ovsx publish --no-dependencies -p ${{ secrets.OVSX_PAT }}
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
